name: Continuous Integration Testing

on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x, 1.19.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    services:
      mongodb:
        image: mongo
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test ./...
